Items List Feature
hungps/flutter_pokedex pull request #48
Opened 2021-11-26 13:14 UTC by LucasFab

Hello,

This Pull Request is based on the add of the Items List to the Pokedex.

I created the repository, providers, use_cases to manage the data. I had to create my own gist to manage the data of the items, if you want to create it yourself tell me and give me the URL and I will change the URL in the repository.

For the front-end part I chose to stay with something quite similar to the list of the pokemon in the pokedex, meaning that you have a list of the items with an image and the name of the item (and the category of it).

Unfortunately, some items on the json data had a correct URL but there was only one white pixel on this URL for the image so some items don't have an image.

Feel free to comment any suggestions to make it better !

2021-11-26 14:18 UTC, scitbiz commented
Hi @LucasFab, thanks for your contribution!
It will be nice if you could attach some screenshots or videos about your new screen.

2021-11-26 14:29 UTC, scitbiz commented
@LucasFab 
Because the repository is in my account so that it's better that I'm the one who keeps all the related stuff about the project.
I've copied your gist, so this is the URL: 
`https://gist.githubusercontent.com/scitbiz/69bb2082702ecbdf3d26cd7ba2a2e00d/raw/pokemon_items.json`

2021-11-26 14:30 UTC, LucasFab commented
> Hi @LucasFab, thanks for your contribution! It would be nice if you could attach some screenshots or videos about your new screen.

I will add the screenshots

2021-11-26 14:32 UTC, LucasFab commented
> @LucasFab Because the repository is in my account so that it's better that I'm the one who keeps all the related stuff about the project. I've copied your gist, so this is the URL. Thank you! `https://gist.githubusercontent.com/scitbiz/69bb2082702ecbdf3d26cd7ba2a2e00d/raw/pokemon_items.json`

Ok I will make the modification, thanks for the answers

2021-11-26 16:42 UTC, LucasFab commented
![Simulator Screen Shot - iPhone 12 - 2021-11-26 at 17 41 51](https://user-images.githubusercontent.com/37048180/143611018-1bef1a87-3d67-46aa-a968-7409bbd48350.png)

Here is a screenshot of the items list

2021-11-26 17:10 UTC, Hugovidafe commented
I've checked the pr with my Redmi Note 8 Pro and I've not noticed any problem ^^

![image](https://user-images.githubusercontent.com/69076992/143613621-d5313a77-0045-41a9-889d-ed93cf292a46.png)

2021-11-27 05:23 UTC, scitbiz requested changes
@LucasFab Everything looks good except for the load more feature is missing and the list are currently being duplicated whenever you scrolled to the bottom of the list instead. Please reconsider adding it or remove it completely. Thanks for your contribution!

2021-11-27 05:23 UTC, scitbiz commented on lib/data/source/github/github_datasource.dart
>    final NetworkManager networkManager;
Please add a new line between static variable and the constructor

2021-11-27 05:23 UTC, scitbiz commented on lib/data/source/local/local_datasource.dart
> +    return pokemonBox.length > 0 && itemBox.length > 0;
Please add a new line before the return statement

2021-11-27 05:23 UTC, scitbiz commented on lib/domain/entities/item.dart
> +      {@required this.name, @required this.image, @required this.category, @required this.effect});
```suggestion
      {@required this.name, @required this.image, @required this.category, @required this.effect,});
```
Please add a  trailing `,` to make the formatter works correctly

2021-11-27 05:23 UTC, scitbiz commented on lib/routes.dart
>        case _Paths.home:
Please add a new line to  separate between cases

2021-11-27 05:23 UTC, scitbiz commented on lib/ui/screens/items_list/items_list.dart
> +    );*/
Please remove all unnecessary comments

2021-11-27 05:23 UTC, scitbiz commented on lib/ui/screens/items_list/widgets/items_grid.dart
> +      context.read(itemStateProvider).getItems();
Either add a load more feature or remove it. The list is currently duplicating everything when you scrolled  to the bottom of the list

2021-12-01 13:23 UTC, LucasFab commented
I did the modification acording to the PR requirements comments

2021-12-05 11:27 UTC, scitbiz commented
Hi @LucasFab, your PR has conflict, please take a look and resolve it

2022-04-03 13:15 UTC, hungps commented
Finished in #58

2022-04-03 13:15 UTC, closed without merging